// Ambient Expo types (CSS side-effect imports, router typed routes, etc.).
// The template's root expo-env.d.ts is gitignored and only generated by `expo start`,
// so a clean checkout (CI, fresh clone) needs this reference to typecheck.
/// <reference types="expo/types" />
